name: coronavirus
description: An application to show latest informations about coronavirus
version: 1.1.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  provider: ^4.0.2
  intl: ^0.16.1
  rxdart: ^0.23.1
  connectivity: ^0.4.6+2
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
